### ISSUE TITLE
Error when including package from npm

### ISSUE THREAD

**Issue by justindh** [karnthis/esiil#1]
did npm install --save esiio

code:
```const { Authenticate } = require('esiio')```

command run:
```
node app.js

```

Error Received:
```
\node_modules\esiio\classes\Character.js:47
  contacts = {
           ^

SyntaxError: Unexpected token =
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (evesso-firebase\functions\node_modules\esiio\index.js:4:19)
```

**Comment by karnthis** [comment]
Looking into this, oddly did not happen in my testing
